version: "3.8"
services:
  mongo:
    image: "mongo:4.2"
    volumes:
      - "mongo_data:/data/db"
    restart: "always"

  elasticsearch:
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      http.host: "0.0.0.0"
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "es_data:/usr/share/elasticsearch/data"
    restart: "always"

  graylog:
    image: "graylog/graylog:4.0"
    depends_on:
      elasticsearch:
        condition: "service_started"
      mongo:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: "somepasswordpepper"
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_PUBLISH_URI: "http://localhost:9000/"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_HTTP_ENABLE_CORS: "true"
      # To make reporting (headless_shell) work inside a Docker container
      GRAYLOG_REPORT_DISABLE_SANDBOX: "true"
    links:
    - "mongo"
    - "elasticsearch"
    ports:
    - "5044:5044/tcp"   # Beats
    - "5140:5140/udp"   # Syslog
    - "5140:5140/tcp"   # Syslog
    - "5555:5555/tcp"   # RAW TCP
    - "5555:5555/udp"   # RAW TCP
    - "9000:9000/tcp"   # Server API
    - "12201:12201/tcp" # GELF
    - "12201:12201/udp" # GELF
    - "10000:10000/tcp" # Custom
    - "10000:10000/udp" # Custom
    - "10001:10001/tcp" # Custom
    - "10001:10001/udp" # Custom
    - "10002:10002/tcp" # Custom
    - "10002:10002/udp" # Custom
    - "10003:10003/tcp" # Custom
    - "10003:10003/udp" # Custom
    - "10004:10004/tcp" # Custom
    - "10004:10004/udp" # Custom
    - "10005:10005/tcp" # Custom
    - "10005:10005/udp" # Custom
    - "10006:10006/tcp" # Custom
    - "10006:10006/udp" # Custom
    - "10007:10007/tcp" # Custom
    - "10007:10007/udp" # Custom
    - "10008:10008/tcp" # Custom
    - "10008:10008/udp" # Custom
    - "10009:10009/tcp" # Custom
    - "10009:10009/udp" # Custom
    - "10010:10010/tcp" # Custom
    - "10010:10010/udp" # Custom
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    restart: "always"
volumes:
  mongo_data:
  es_data:
  graylog_data:
  graylog_journal:
